# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Necessary edits
command_timeout = 800

# ~~~~ Core format ~~~~
format = """
[░▒▓](#a3aed2)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_state\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$python\
$c\
$conda\
[](fg:#212736 bg:#1d2230)\
$docker_context\
$shell\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""

# the beginning prompt char
[character]
success_symbol = "[➜](green)"
error_symbol = "[✖](bold red) "

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# this is dumb
# [directory.substitutions]
# "Documents" = " "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "

# disable aws
[aws]
disabled = true

# ~~~~ Git prompts ~~~~
[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# ~~~~ Language prompts ~~~~
[c]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[conda]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol$environment ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# ~~~~ General system util prompts ~~~~
[shell]
fish_indicator = ''
powershell_indicator = '_'
zsh_indicator = ''
unknown_indicator = 'mystery shell'
style = "bg:#1d2230"
disabled = false
format = '[[ $indicator ](fg:#769ff0 bg:#1d2230)]($style)'

[docker_context]
symbol = " "
style = "bg:#1d2230"
format = '[[ $symbol$context ](fg:#769ff0 bg:#1d2230)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[cmd_duration]
style = "bg:#1d2230"
format = '[[  $duration ](fg:#a0a9cb bg:#1d2230)]($style)'
